apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app1-chart.fullname" . }}-secret
  labels:
    {{ include "app1-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
